fix: adds an action when only one of the required for MCT was ignored
forcedotcom/source-deploy-retrieve pull request #494
Opened 2021-11-03 21:35 UTC by WillieRuemmele

### What does this PR do?
when you have a remote-only Apex class like Class1
and have the entry `**/Class1.cls` in the `.forceignore` file, a retrieve would error with 
`ERROR running force:source:retrieve: Metadata API request failed: ApexClass types require source to be present and unpackaged/classes/Class1.cls is forceignored.`

new message:
`Metadata API request failed: ApexClass types require source to be present and unpackaged/classes/Class1.cls is forceignored. 
 ACTION: Both the content file, and -meta.xml file must be ignored, try appending * to your .forceignore entry`

this could lead to a confusing behavior if you're new to sfdx dev. "I ignored the class, why can't I retrieve it", it's because that metadata type _actually_ has two files that both must be ignored

this adds a message to ignore the `.cls`(example) and `-meta.xml` file for all MatchingContentType metadata types

### What issues does this PR fix or reference?

@W-10037182@ https://github.com/forcedotcom/cli/issues/1238

2021-11-08 15:47 UTC, mshanemc approved these changes

2021-11-08 15:47 UTC, mshanemc commented on src/i18n/i18n.ts
> +    '%s types require source to be present and %s is forceignored. \n ACTION: Both the content file, and -meta.xml file must be ignored, try appending * to your .forceignore entry',
```suggestion
    '%s types require source to be present and %s is forceignored. \n ACTION: Both the content file and -meta.xml file must be ignored.  Try appending * to your .forceignore entry',
```

2021-11-08 15:56 UTC, randi274 approved these changes

2021-11-08 22:20 UTC, jshackell-sfdc commented on src/i18n/i18n.ts
>    error_missing_type_definition: "Missing metadata type definition in registry for id '%s'",
```suggestion
  error_missing_type_definition: "Missing metadata type definition in registry for id '%s'.",
```

2021-11-08 22:23 UTC, jshackell-sfdc requested changes

2021-11-08 22:23 UTC, jshackell-sfdc commented on src/i18n/i18n.ts
>    error_missing_child_type_definition: 'Type %s does not have a child type definition %s',
```suggestion
  error_missing_child_type_definition: 'Type %s does not have a child type definition %s.',
```

2021-11-08 22:23 UTC, jshackell-sfdc commented on src/i18n/i18n.ts
>    error_no_metadata_xml_ignore: 'Metadata xml file %s is forceignored but is required for %s',
```suggestion
  error_no_metadata_xml_ignore: 'Metadata xml file %s is forceignored but is required for %s.',
```

2021-11-08 22:23 UTC, jshackell-sfdc commented on src/i18n/i18n.ts
>    error_no_directory_stream: '%s does not support readable streams on directories',
```suggestion
  error_no_directory_stream: '%s doesn\'t support readable streams on directories.',
```

2021-11-08 22:23 UTC, jshackell-sfdc commented on src/i18n/i18n.ts
>    error_no_source_to_deploy: 'No source backed components present in the package',
```suggestion
  error_no_source_to_deploy: 'No source-backed components present in the package.',
```

2021-11-08 22:23 UTC, jshackell-sfdc commented on src/i18n/i18n.ts
>    error_no_components_to_retrieve: 'No components in the package to retrieve',
```suggestion
  error_no_components_to_retrieve: 'No components in the package to retrieve.',
```

2021-11-08 22:23 UTC, jshackell-sfdc commented on src/i18n/i18n.ts
> +  error_invalid_package: 'The metadata package was not initialized properly',
```suggestion
  error_invalid_package: 'The metadata package wasn\'t properly initialized.',
```

2021-11-08 22:23 UTC, jshackell-sfdc commented on src/i18n/i18n.ts
>      'A StaticResource directory must have a content type of application/zip or application/jar - found %s for %s',
```suggestion
    'A StaticResource directory must have a content type of application/zip or application/jar - found %s for %s.',
```

2021-11-10 21:44 UTC, cristiand391 approved these changes
QA:
Created and empty project, created apex class `Class1` and `Class2` from org ui, forceignore file:
```
...
**/Class1.cls
```
```
sfdx force:source:retrieve --metadata=ApexClass
ERROR running force:source:retrieve:  Metadata API request failed: ApexClass metadata types require source files, but unpackaged/classes/Class1.cls is forceignored.
        ACTION: Metadata types with content are composed of two files: a content file (ie MyApexClass.cls) and a -meta.xml file (i.e MyApexClass.cls-meta.xml). You must include both files in your .forceignore file. Or try appending “*” to your existing .forceignore entry.
```

2021-11-10 21:45 UTC, merged