fix: add ComponentSetBuilder from plugin-source
forcedotcom/source-deploy-retrieve pull request #576
Opened 2022-02-14 21:32 UTC by WillieRuemmele

### What does this PR do?
adds the `ComponentSetBuilder` the CLI team has been using in `plugin-source` to create CS

other consumers of SDR might find it useful as well as `sf` source plugin

### What issues does this PR fix or reference?

@W-10657718@

### Functionality Before
N/A

### Functionality After
Use the component set builder to create component sets from a variety of sources, set api versions on the connection

2022-02-15 02:40 UTC, mshanemc requested changes
2 minor changes, please

2022-02-15 02:40 UTC, mshanemc commented on src/collections/componentSetBuilder.ts
> +          fsPaths.push(path.resolve(filepath));
```suggestion
        const fsPaths =  sourcepath.map((filepath) => {
          if (!fs.existsSync(filepath)) {
            throw new SfdxError(`The sourcepath "${filepath}" is not a valid source file path.`);
          }
          return path.resolve(filepath);
```

2022-02-15 02:40 UTC, mshanemc commented on src/collections/componentSetBuilder.ts
> +          resolveSourcePaths: options.manifest.directoryPaths,
why not use `directoryPaths` since there's already a const?

2022-02-15 23:23 UTC, mshanemc reviewed
I don't have any problems with what this does.

My only concern is that we have @jayree 's PR open here https://github.com/salesforcecli/plugin-source/pull/423 and we want that in as well.  So either add that stuff if @shetzel  says it's "done" OR hold off on this and then copy-paste that when it is done

2022-02-15 23:34 UTC, WillieRuemmele commented
In draft until https://github.com/salesforcecli/plugin-source/pull/423 has been finalized

2022-02-28 16:44 UTC, shetzel requested changes

2022-02-28 16:44 UTC, shetzel commented on src/collections/componentSetBuilder.ts
> +      if (org) {
This is where I think we'll have to add some validation of `ComponentSetOptions`.  I can't think of a reason why someone would want to combine the `org` option with others, but line 121 below will clobber `componentSet` anyway.  Either the reassignment should change to be additive or we need to validate how people are combining `ComponentSetOptions`.

2022-02-28 16:44 UTC, shetzel commented on src/collections/componentSetBuilder.ts
> +    if (logger.debugEnabled && componentSet.size) {
I've noticed that `logger.debugEnabled` doesn't seem to be working properly.  Probably a bug in sfdx-core.

2022-03-01 16:30 UTC, shetzel commented on src/collections/componentSetBuilder.ts
> +    if (componentSet?.size) {
sorry I wasn't clear with my comment. The `logger.debugEnabled` condition needs to be there so this doesn't execute unless debug is enabled.  I just meant it wasn't working in practice for some reason.

2022-03-01 22:06 UTC, merged