Sm/zip reads readables earlier
forcedotcom/source-deploy-retrieve pull request #683
Opened 2022-08-04 17:08 UTC by mshanemc

### What does this PR do?

zip operation is probably the most common thing SDR does (every push/deploy)
ZipWriter passed all the WriteInfos to Archiver as Readable
Before this PR, all those Readable remained open until the zip finalizes.
So that would hit windows file limits but only on the zip operations (source->metadata and metada->source formats worked fine).  

This PR moves the reading of those files **left** in the pipeline, so that they're read into buffers as they come in (using existing utility code) and then passed to Archiver.  Once a file is read into buffer, the stream closes and the file doesn't have to stay open.

Besides solving the bug for windows users, this also has some perf benefits for all users (compare the passing scale nut from the 2 circle jobs shown below, or the checked in perf stats for linux/mac)

fix #578 . 

### What issues does this PR fix or reference?

#<Insert GitHub Issue>, @<Insert GUS WI>@
[@W-11492994@](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000012HtqzYAC/view)
fix https://github.com/forcedotcom/cli/issues/1555 

### Functionality Before

https://app.circleci.com/pipelines/github/forcedotcom/source-deploy-retrieve/4345/workflows/e4e5f01c-5eaa-4b9c-becb-1d23dcf358a0/jobs/19752)

### Functionality After

https://app.circleci.com/pipelines/github/forcedotcom/source-deploy-retrieve/4351/workflows/f664546c-54fd-430e-a8ab-4a16dfec1d87/jobs/19817

2022-08-04 19:07 UTC, WillieRuemmele reviewed
couldn't get those tests working?

any idea why the `sourceToMdapi` time increased across the board? While the other three decreased?

2022-08-04 19:42 UTC, mshanemc commented
> couldn't get those tests working?
> 
> any idea why the `sourceToMdapi` time increased across the board? While the other three decreased?

got them back now.  It's the typical UT scenario--the tests are deeply tied to the implementation.  I just wanted the NUTs to run to tell me I wasn't crazy (and they caught a real bug in folder types) before investing the time rewriting the UT

2022-08-04 19:51 UTC, mshanemc commented
> any idea why the `sourceToMdapi` time increased across the board? While the other three decreased?

whatever it is, it's not affected by this change to the zip writer.  anything that's < 1 second of change I'm gonna consider noise (after observing these for a while).

2022-08-11 03:04 UTC, RodEsp requested changes
I was successfully able to run the perf NUTs with the new code and would intermittently get the "too many files open" error with the old code. Something to note though is that in both scenarios they took 30+ minutes to run 😕

I just have two very small comments but after those are addressed feel free to merge this at your convenience @mshanemc.

2022-08-11 12:35 UTC, mshanemc commented on .circleci/config.yml
> +      - release-management/test-nut:
good idea.  I made a change to do that

2022-08-11 13:46 UTC, merged